id: P001689
initial_creation_type: ocr
created_at: 24/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W17320
  title: པདྨ་བཀའ་ཐང
  author: ''
  volumes:
    5edd4ab60ad84dfaa65b672e3e51d49b:
      image_group_id: I1PD36420
      title: ''
      volume_number: 1
      total_pages: 834
      base_file: v001.txt
