id: IFAB4F721
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-24T20:30:56+00:00'
last_modified: '2022-06-07T14:02:01.008215+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W17320
  title: པདྨ་བཀའ་ཐང
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    '6594':
      image_group_id: I1PD36420
      title: ''
      total_pages: 834
      order: 1
      base_file: 6594.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
